// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-h5e8ZEqEw_o4noPbag2YODe1RxX9jrI',
    appId: '1:339705734526:web:2be87a1825d1b99f727f2f',
    messagingSenderId: '339705734526',
    projectId: 'restaurant-system-48d55',
    authDomain: 'restaurant-system-48d55.firebaseapp.com',
    storageBucket: 'restaurant-system-48d55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3vwgXyS2UhItcvYRQrrNbkGU0GWOpkE',
    appId: '1:339705734526:android:1fcee1bdb5a238fd727f2f',
    messagingSenderId: '339705734526',
    projectId: 'restaurant-system-48d55',
    storageBucket: 'restaurant-system-48d55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kLG19TTKQvbxLXaKVWqBYofHmlcxtV4',
    appId: '1:339705734526:ios:2271d11a159860e1727f2f',
    messagingSenderId: '339705734526',
    projectId: 'restaurant-system-48d55',
    storageBucket: 'restaurant-system-48d55.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kLG19TTKQvbxLXaKVWqBYofHmlcxtV4',
    appId: '1:339705734526:ios:2271d11a159860e1727f2f',
    messagingSenderId: '339705734526',
    projectId: 'restaurant-system-48d55',
    storageBucket: 'restaurant-system-48d55.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-h5e8ZEqEw_o4noPbag2YODe1RxX9jrI',
    appId: '1:339705734526:web:fcc6a9499aee3e3d727f2f',
    messagingSenderId: '339705734526',
    projectId: 'restaurant-system-48d55',
    authDomain: 'restaurant-system-48d55.firebaseapp.com',
    storageBucket: 'restaurant-system-48d55.firebasestorage.app',
  );
}
